source 'https://api.berkshelf.com'

cookbook 'apt', '~> 2.6.0'
cookbook 'vim', '~> 1.1.2'
cookbook 'git', '~> 4.0.2'
cookbook 'postgresql', '~> 3.4.10'
cookbook 'sqlite', '~> 1.1.0'
cookbook 'nodejs', '~> 2.1.0'
cookbook 'brightbox-ruby', '~> 1.2.0'
cookbook 'reaper', '~> 1.0.0', path: 'chef/cookbooks/reaper'
